### ISSUE TITLE
Add core files?

### ISSUE THREAD

**Issue by cnvo** [ever-co/feature-requests#1]
Hello, so far so good. I was wondering when will you be adding the core files that actually make up the app itself, including web panels and more.

**Comment by evereq** [comment]
Hello @cnvo, we are going to release "core" after all holidays, more close to the end of January 2019.
We will keep you posted, thank you for your interest in our software! Meanwhile, if you have more questions, feel free to email us: ever at ever.co

**Comment by cnvo** [comment]
Thanks, I look forward to seeing this platform grow and would love to contribute with ideas/feedback. I'll close this issue, since the question has been answered. Happy Holidays!

**Comment by evereq** [comment]
To track progress on the release, see https://github.com/ever-co/ever/projects/1

**Comment by evereq** [comment]
@cnvo it takes longer than expected (as everything good in our life), but today we released all platform apps on Github, enjoy! 🚀
