### ISSUE TITLE
Question: How does Geolocation work?

### ISSUE THREAD

**Issue by cnvo** [ever-co/feature-requests#3]
In its current state, how is countries, cities, regions/area defined?
How is the radius of a given area for delivery defined?

**Comment by evereq** [comment]
@cnvo as of today we only support "radius" based proximity search. 
E.g. customer will see offers from stores located within 50km radius from him (50km is just some constant you can change). 

We know it's not enough for many scenarios, but it's the basic way which we think solve maybe 80% of use cases. For the rest 20% we will work to add other types of proximity searches. For example, see https://docs.mongodb.com/manual/tutorial/geospatial-tutorial/, where there is an example of how to implement search in the Neighborhood.

So essentially we will support many different types of area selection to which given merchant deliver. It can be city, region/neighborhood, some radius, etc. 

P.S. If you have some specific requirements, do let us know in comments here. Thanks!
