### ISSUE TITLE
WebShop and MobileShop: Allow adding location details to the customer making a purchase from the shop

### ISSUE THREAD

**Issue by morggansoft** [ever-co/feature-requests#40]
Allow adding location details to the customer making a purchase from the shop. 
For example: Blue door, hall at the bottom, knock on the door, dangerous dog, etc.
This makes it easier for the deliveryman to deliver merchandise.

Basically we need to add multi-line input (e.g. 3 lines max) where customer can add "Location Notes" when he registers address (in mobile shop app, in the web shop, show it in Admin, in Merchant app for order, in Carrier app for delivery, etc)

Note: it is different from #36 because here we talk about the registration page (customer address), not about the order page! I.e. it's the ability to add some notes for customer address which is important in this ticket, but #36 talks about the ability to add some notes only to specific order!

**Comment by evereq** [comment]
I.e. on page https://github.com/ever-co/ever-docs/blob/master/docs/assets/shop/mobile/auth/signup_address2.png, we can add a tiny link called "Location Notes" (say to the left in the same line where we have apartment checkbox. If user clicks on that link, we will display multi-line input for location notes and store them in the same place where we store location (i.e. basically think in the code address will have one more field, in addition to city, street, etc, we will have notes field)

**Comment by YavorGrancharov** [comment]
Done!
![Inked4YEcaXVTwd_LI](https://user-images.githubusercontent.com/28997304/85819249-c8720f00-b77b-11ea-8628-f7cf1b50532c.jpg)
![InkedvCdgL1unK0_LI](https://user-images.githubusercontent.com/28997304/85819259-cf008680-b77b-11ea-9f04-33d10009cebe.jpg)
![InkedqAtAp1R2GF_LI](https://user-images.githubusercontent.com/28997304/85819271-daec4880-b77b-11ea-856f-5c235bd71cfd.jpg)
![InkedUY7FthExhx_LI](https://user-images.githubusercontent.com/28997304/85819284-e17ac000-b77b-11ea-8b05-44f23f89f19d.jpg)
![InkedmpeHJqMene_LI](https://user-images.githubusercontent.com/28997304/85819329-066f3300-b77c-11ea-9640-a22556165639.jpg)
