### ISSUE TITLE
Merchant: Allow the merchant to see if an ongoing order is takeaway or delivery

### ISSUE THREAD

**Issue by morggansoft** [ever-co/feature-requests#48]
Show in the order if it is for delivery or takeaway

![image](https://user-images.githubusercontent.com/59708947/76902788-82073d00-687b-11ea-8868-a4b6269d4c61.png)

**Comment by YavorGrancharov** [comment]
Done!
![85830726-ba30ec80-b795-11ea-84c7-7377a6cefc1a](https://user-images.githubusercontent.com/28997304/86121121-238a6580-bade-11ea-83cb-d6b83c1f922f.jpg)
